#!/usr/bin/env bash
# Install Agent Brain Cursor plugin (hosted SSE + hooks).
# Usage:
#   ./plugins/cursor/install.sh --global \
#     --url https://agent-memory.nighthawklabs.org/sse \
#     --agent-id cursor-agent \
#     --api-key YOUR_KEY
#     --version v1.0.0   # optional mcp-call release (default: latest)
#
# Or --project to install into the current repo's .cursor/ directory.
#
# Remote (no clone needed):
#   curl -fsSL https://raw.githubusercontent.com/realnighthawk/agent-plugins/main/plugins/cursor/install.sh | bash -s -- --global --api-key ...
set -euo pipefail

PLUGIN_GITHUB_REPO="${AGENT_PLUGINS_GITHUB_REPO:-realnighthawk/agent-plugins}"
AGENT_PLUGINS_REF="${AGENT_PLUGINS_REF:-main}"

# Detect if running from a local checkout (dev workflow — enables go build fallback for mcp-call).
_script_path="${BASH_SOURCE[0]:-}"
LOCAL_CHECKOUT=""
if [[ -n "${_script_path}" ]]; then
  _lib="$(cd "$(dirname "${_script_path}")/../.." 2>/dev/null && pwd)/scripts/lib/install-repo.sh"
  if [[ -f "${_lib}" ]]; then
    # shellcheck source=../../scripts/lib/install-repo.sh
    . "${_lib}"
    LOCAL_CHECKOUT="$(plugins_repo_root "${_script_path}")"
  fi
fi

SCOPE="global"
MCP_URL="https://agent-memory.nighthawklabs.org/sse"
AGENT_ID=""
API_KEY="${NIGHTHAWK_API_KEY:-}"
JWT="${NIGHTHAWK_JWT:-}"
USER_TAG="${USER:-you}"
MCP_CALL_VERSION="${MCP_CALL_VERSION:-latest}"

usage() {
  sed -n '2,12p' "${BASH_SOURCE[0]:-$0}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --global) SCOPE="global"; shift ;;
    --project) SCOPE="project"; shift ;;
    --url) MCP_URL="$2"; shift 2 ;;
    --agent-id) AGENT_ID="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --jwt) JWT="$2"; shift 2 ;;
    --user) USER_TAG="$2"; shift 2 ;;
    --version) MCP_CALL_VERSION="$2"; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  if [[ "$SCOPE" == "project" ]]; then
    AGENT_ID="cursor-${USER_TAG}-$(basename "$PWD")"
  else
    AGENT_ID="cursor-${USER_TAG}"
  fi
fi

if [[ -z "$API_KEY" && -z "$JWT" ]]; then
  echo "Provide --api-key or --jwt (or set NIGHTHAWK_API_KEY / NIGHTHAWK_JWT)." >&2
  exit 1
fi

if [[ "$SCOPE" == "global" ]]; then
  CURSOR_DIR="${HOME}/.cursor"
  HOOK_CMD_PREFIX="${CURSOR_DIR}/hooks"
else
  CURSOR_DIR="${PWD}/.cursor"
  HOOK_CMD_PREFIX=".cursor/hooks"
fi

mkdir -p "${CURSOR_DIR}/bin" "${CURSOR_DIR}/hooks/lib" "${CURSOR_DIR}/state"

# Fetch plugin files from local checkout or GitHub tarball.
fetch_plugin_files() {
  local src tmpdir=""
  if [[ -n "${LOCAL_CHECKOUT}" ]]; then
    src="${LOCAL_CHECKOUT}/plugins/cursor"
  else
    local url
    tmpdir=$(mktemp -d)

    if [[ "$AGENT_PLUGINS_REF" == v* ]]; then
      url="https://github.com/${PLUGIN_GITHUB_REPO}/archive/refs/tags/${AGENT_PLUGINS_REF}.tar.gz"
    else
      url="https://github.com/${PLUGIN_GITHUB_REPO}/archive/refs/heads/${AGENT_PLUGINS_REF}.tar.gz"
    fi

    echo "Fetching cursor plugin files from GitHub..."
    curl -fsSL "$url" | tar -xz -C "$tmpdir"
    src="$(ls -d "$tmpdir"/*/plugins/cursor)"
  fi

  cp -R "${src}/hooks/"*.sh "${CURSOR_DIR}/hooks/"
  cp -R "${src}/hooks/lib/"*.sh "${CURSOR_DIR}/hooks/lib/"
  chmod +x "${CURSOR_DIR}/hooks/"*.sh "${CURSOR_DIR}/hooks/lib/"*.sh
  [[ -n "$tmpdir" ]] && rm -rf "$tmpdir"
}

# Install mcp-call binary to DEST.
# Local dev checkouts delegate to the full fetch script (supports go build fallback).
# Remote installs download directly from GitHub releases.
install_mcp_call() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"

  if [[ -n "${LOCAL_CHECKOUT}" && -f "${LOCAL_CHECKOUT}/scripts/fetch-mcp-call.sh" ]]; then
    export MCP_CALL_VERSION
    "${LOCAL_CHECKOUT}/scripts/fetch-mcp-call.sh" "$dest"
    return
  fi

  local os_name arch asset repo ver url tmp
  case "$(uname -s)" in
    Darwin) os_name=darwin ;;
    Linux)  os_name=linux ;;
    *) echo "unsupported OS: $(uname -s)" >&2; return 1 ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) echo "unsupported arch: $(uname -m)" >&2; return 1 ;;
  esac

  asset="mcp-call-${os_name}-${arch}"
  repo="${NIGHTHAWK_MCP_CALL_REPO:-realnighthawk/agent-plugins}"
  ver="${MCP_CALL_VERSION:-latest}"
  if [[ -z "$ver" || "$ver" == "latest" ]]; then
    url="https://github.com/${repo}/releases/latest/download/${asset}"
  else
    url="https://github.com/${repo}/releases/download/v${ver#v}/${asset}"
  fi

  tmp="${dest}.$$.tmp"
  echo "Downloading mcp-call (${asset})..."
  curl -fsSL "$url" -o "$tmp"
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"
  echo "Installed ${dest} from release"
}

echo "Installing mcp-call..."
install_mcp_call "${CURSOR_DIR}/bin/mcp-call"

echo "Copying hooks..."
fetch_plugin_files

ENV_FILE="${CURSOR_DIR}/agent-brain.env"
cat >"$ENV_FILE" <<EOF
# Agent Brain Cursor plugin — generated by install.sh
NIGHTHAWK_MCP_URL=${MCP_URL}
NIGHTHAWK_AGENT_ID=${AGENT_ID}
EOF
chmod 600 "$ENV_FILE"

if [[ -n "$JWT" ]]; then
  echo "NIGHTHAWK_JWT=${JWT}" >>"$ENV_FILE"
else
  echo "NIGHTHAWK_API_KEY=${API_KEY}" >>"$ENV_FILE"
fi

# hooks.json with correct paths for global vs project
cat >"${CURSOR_DIR}/hooks.json" <<EOF
{
  "version": 1,
  "hooks": {
    "sessionStart": [
      {
        "command": "${HOOK_CMD_PREFIX}/session-start.sh",
        "timeout": 15
      }
    ],
    "beforeSubmitPrompt": [
      {
        "command": "${HOOK_CMD_PREFIX}/recall.sh",
        "matcher": "UserPromptSubmit",
        "timeout": 30
      }
    ],
    "afterAgentResponse": [
      {
        "command": "${HOOK_CMD_PREFIX}/index.sh",
        "timeout": 30
      }
    ],
    "stop": [
      {
        "command": "${HOOK_CMD_PREFIX}/index.sh",
        "timeout": 15
      }
    ]
  }
}
EOF

# mcp.json — Cursor HTTP/SSE ignores envFile; ${NIGHTHAWK_*} is not expanded. Inline secrets at install.
MCP_DEST="${CURSOR_DIR}/mcp.json"
if [[ -n "$JWT" ]]; then
  NEW_MCP="$(jq -n \
    --arg url "$MCP_URL" \
    --arg jwt "$JWT" \
    --arg agent "$AGENT_ID" \
    '{
      mcpServers: {
        "agent-brain": {
          type: "http",
          url: $url,
          headers: {
            Authorization: ("Bearer " + $jwt),
            "X-Agent-ID": $agent
          }
        }
      }
    }')"
else
  NEW_MCP="$(jq -n \
    --arg url "$MCP_URL" \
    --arg key "$API_KEY" \
    --arg agent "$AGENT_ID" \
    '{
      mcpServers: {
        "agent-brain": {
          type: "http",
          url: $url,
          headers: {
            "X-API-Key": $key,
            "X-Agent-ID": $agent
          }
        }
      }
    }')"
fi
if [[ -f "$MCP_DEST" ]]; then
  jq -s '.[0].mcpServers["agent-brain"] = .[1].mcpServers["agent-brain"] | .[0]' \
    "$MCP_DEST" <(echo "$NEW_MCP") >"${MCP_DEST}.tmp" && mv "${MCP_DEST}.tmp" "$MCP_DEST"
  echo "Merged agent-brain into ${MCP_DEST} (credentials inlined for Cursor MCP)"
else
  echo "$NEW_MCP" >"$MCP_DEST"
  echo "Wrote ${MCP_DEST} (credentials inlined for Cursor MCP)"
fi
chmod 600 "$MCP_DEST"

echo ""
echo "Installed Agent Brain Cursor plugin (${SCOPE})"
echo "  MCP URL:     ${MCP_URL}"
echo "  Agent ID:    ${AGENT_ID}"
echo "  Env file:    ${ENV_FILE}"
echo "  Hooks:       ${CURSOR_DIR}/hooks.json"
echo ""
echo "Server checklist:"
echo "  1. Memory Explorer → Settings: register agent \"${AGENT_ID}\" (iam_service_accounts)"
echo "  2. Create API key or JWT in Settings if you did not pass --api-key / --jwt"
echo ""
echo "MCP note: ${ENV_FILE} is for hooks/mcp-call only. Cursor remote MCP does not load envFile or \${NIGHTHAWK_*}."
echo "Next: restart Cursor, enable Hooks (Settings), check Hooks output channel."
echo "Smoke test:"
echo "  set -a && source ${ENV_FILE} && set +a"
echo "  ${CURSOR_DIR}/bin/mcp-call memory_system_status '{}'"
