#!/usr/bin/env bash
# Install Agent Brain Cursor plugin (hosted SSE + hooks).
# Usage:
#   ./plugins/cursor/install.sh --global \
#     --url https://agent-memory.nighthawklabs.org/sse \
#     --agent-id cursor-agent \
#     --api-key YOUR_KEY
#     --version v1.0.0   # optional mcp-call release (default: latest)
#
# Or --project to install into the current repo's .cursor/ directory.
#
# Remote (no clone):
#   curl -fsSL https://raw.githubusercontent.com/realnighthawk/agent-plugins/main/plugins/cursor/install.sh | bash -s -- --global --api-key ...
set -euo pipefail

# Bootstrap lib (curl | bash has no BASH_SOURCE — fetch install-repo.sh from GitHub).
_script_path="${BASH_SOURCE[0]:-}"
_lib=""
if [[ -n "${_script_path}" ]]; then
  _lib="$(cd "$(dirname "${_script_path}")/../.." 2>/dev/null && pwd)/scripts/lib/install-repo.sh"
fi
if [[ -n "${_lib}" && -f "${_lib}" ]]; then
  # shellcheck source=../../scripts/lib/install-repo.sh
  . "${_lib}"
else
  _bootstrap="$(mktemp)"
  curl -fsSL "https://raw.githubusercontent.com/realnighthawk/agent-plugins/main/scripts/lib/install-repo.sh" -o "${_bootstrap}"
  # shellcheck source=/dev/null
  . "${_bootstrap}"
  rm -f "${_bootstrap}"
fi
plugins_install_setup cursor "${_script_path}"
ROOT="${PLUGINS_ROOT}"
SCOPE="global"
MCP_URL="https://agent-memory.nighthawklabs.org/sse"
AGENT_ID=""
API_KEY="${NIGHTHAWK_API_KEY:-}"
JWT="${NIGHTHAWK_JWT:-}"
USER_TAG="${USER:-you}"

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --global) SCOPE="global"; shift ;;
    --project) SCOPE="project"; shift ;;
    --url) MCP_URL="$2"; shift 2 ;;
    --agent-id) AGENT_ID="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --jwt) JWT="$2"; shift 2 ;;
    --user) USER_TAG="$2"; shift 2 ;;
    --version) MCP_CALL_VERSION="$2"; shift 2 ;;
    -h|--help) usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  if [[ "$SCOPE" == "project" ]]; then
    base="$(basename "$ROOT")"
    AGENT_ID="cursor-${USER_TAG}-${base}"
  else
    AGENT_ID="cursor-${USER_TAG}"
  fi
fi

if [[ -z "$API_KEY" && -z "$JWT" ]]; then
  echo "Provide --api-key or --jwt (or set NIGHTHAWK_API_KEY / NIGHTHAWK_JWT)." >&2
  exit 1
fi

if [[ "$SCOPE" == "global" ]]; then
  CURSOR_DIR="${HOME}/.cursor"
  HOOK_CMD_PREFIX="${CURSOR_DIR}/hooks"
else
  CURSOR_DIR="${ROOT}/.cursor"
  HOOK_CMD_PREFIX=".cursor/hooks"
fi

mkdir -p "${CURSOR_DIR}/bin" "${CURSOR_DIR}/hooks/lib" "${CURSOR_DIR}/state"

echo "Installing mcp-call..."
export MCP_CALL_VERSION="${MCP_CALL_VERSION:-latest}"
"${ROOT}/scripts/fetch-mcp-call.sh" "${CURSOR_DIR}/bin/mcp-call"

echo "Copying hooks..."
cp -R "${ROOT}/plugins/cursor/hooks/"*.sh "${CURSOR_DIR}/hooks/"
cp -R "${ROOT}/plugins/cursor/hooks/lib/"*.sh "${CURSOR_DIR}/hooks/lib/"
chmod +x "${CURSOR_DIR}/hooks/"*.sh "${CURSOR_DIR}/hooks/lib/"*.sh "${CURSOR_DIR}/bin/mcp-call"

ENV_FILE="${CURSOR_DIR}/agent-brain.env"
cat >"$ENV_FILE" <<EOF
# Agent Brain Cursor plugin — generated by install.sh
NIGHTHAWK_MCP_URL=${MCP_URL}
NIGHTHAWK_AGENT_ID=${AGENT_ID}
EOF
chmod 600 "$ENV_FILE"

if [[ -n "$JWT" ]]; then
  echo "NIGHTHAWK_JWT=${JWT}" >>"$ENV_FILE"
else
  echo "NIGHTHAWK_API_KEY=${API_KEY}" >>"$ENV_FILE"
fi

# hooks.json with correct paths for global vs project
cat >"${CURSOR_DIR}/hooks.json" <<EOF
{
  "version": 1,
  "hooks": {
    "sessionStart": [
      {
        "command": "${HOOK_CMD_PREFIX}/session-start.sh",
        "timeout": 15
      }
    ],
    "beforeSubmitPrompt": [
      {
        "command": "${HOOK_CMD_PREFIX}/recall.sh",
        "matcher": "UserPromptSubmit",
        "timeout": 30
      }
    ],
    "afterAgentResponse": [
      {
        "command": "${HOOK_CMD_PREFIX}/index.sh",
        "timeout": 30
      }
    ],
    "stop": [
      {
        "command": "${HOOK_CMD_PREFIX}/index.sh",
        "timeout": 15
      }
    ]
  }
}
EOF

# mcp.json — merge agent-brain server if jq available
NEW_MCP="$(mktemp)"
if [[ -n "$JWT" ]]; then
  cat >"$NEW_MCP" <<EOF
{
  "mcpServers": {
    "agent-brain": {
      "type": "http",
      "url": "${MCP_URL}",
      "envFile": "${ENV_FILE}",
      "headers": {
        "Authorization": "Bearer \${NIGHTHAWK_JWT}",
        "X-Agent-ID": "\${NIGHTHAWK_AGENT_ID}",
        "X-Session-ID": "\${NIGHTHAWK_SESSION_ID}"
      }
    }
  }
}
EOF
else
  sed -e "s|__NIGHTHAWK_MCP_URL__|${MCP_URL}|g" \
      -e "s|__NIGHTHAWK_ENV_FILE__|${ENV_FILE}|g" \
      "${ROOT}/plugins/cursor/templates/mcp.json" >"$NEW_MCP"
fi

MCP_DEST="${CURSOR_DIR}/mcp.json"
if [[ -f "$MCP_DEST" ]] && command -v jq >/dev/null 2>&1; then
  jq -s '.[0].mcpServers["agent-brain"] = .[1].mcpServers["agent-brain"] | .[0]' \
    "$MCP_DEST" "$NEW_MCP" >"${MCP_DEST}.tmp" && mv "${MCP_DEST}.tmp" "$MCP_DEST"
  echo "Merged agent-brain into ${MCP_DEST}"
else
  cp "$NEW_MCP" "$MCP_DEST"
  echo "Wrote ${MCP_DEST}"
fi
rm -f "$NEW_MCP"

echo ""
echo "Installed Agent Brain Cursor plugin (${SCOPE})"
echo "  MCP URL:     ${MCP_URL}"
echo "  Agent ID:    ${AGENT_ID}"
echo "  Env file:    ${ENV_FILE}"
echo "  Hooks:       ${CURSOR_DIR}/hooks.json"
echo ""
echo "Server checklist:"
echo "  1. Memory Explorer → Settings: register agent \"${AGENT_ID}\" (iam_service_accounts)"
echo "  2. Create API key or JWT in Settings if you did not pass --api-key / --jwt"
echo ""
echo "Next: restart Cursor, enable Hooks (Settings), check Hooks output channel."
echo "Smoke test:"
echo "  set -a && source ${ENV_FILE} && set +a"
echo "  ${CURSOR_DIR}/bin/mcp-call memory_system_status '{}'"
