#!/usr/bin/env bash
# Install Agent Brain OpenClaw plugin (hosted SSE + lifecycle hooks).
#
# Usage:
#   ./plugins/openclaw/install.sh \
#     --url https://agent-memory.nighthawklabs.org/sse \
#     --agent-id openclaw-you \
#     --api-key YOUR_KEY
#
# Remote (no clone needed):
#   curl -fsSL https://raw.githubusercontent.com/realnighthawk/agent-plugins/main/plugins/openclaw/install.sh | bash -s -- --api-key ...
set -euo pipefail

PLUGIN_GITHUB_REPO="${AGENT_PLUGINS_GITHUB_REPO:-realnighthawk/agent-plugins}"
AGENT_PLUGINS_REF="${AGENT_PLUGINS_REF:-main}"

# Detect if running from a local checkout (dev workflow — enables go build fallback for mcp-call).
_script_path="${BASH_SOURCE[0]:-}"
LOCAL_CHECKOUT=""
if [[ -n "${_script_path}" ]]; then
  _lib="$(cd "$(dirname "${_script_path}")/../.." 2>/dev/null && pwd)/scripts/lib/install-repo.sh"
  if [[ -f "${_lib}" ]]; then
    # shellcheck source=../../scripts/lib/install-repo.sh
    . "${_lib}"
    LOCAL_CHECKOUT="$(plugins_repo_root "${_script_path}")"
  fi
fi

MCP_URL="https://agent-memory.nighthawklabs.org/sse"
AGENT_ID=""
API_KEY="${NIGHTHAWK_API_KEY:-}"
JWT="${NIGHTHAWK_JWT:-}"
USER_TAG="${USER:-you}"
AGENT_PREFIX="openclaw"
MCP_CALL_VERSION="${MCP_CALL_VERSION:-latest}"
SKIP_PLUGIN_INSTALL=0
RESTART_GATEWAY=0

usage() {
  sed -n '2,11p' "${BASH_SOURCE[0]:-$0}" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url) MCP_URL="$2"; shift 2 ;;
    --agent-id) AGENT_ID="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --jwt) JWT="$2"; shift 2 ;;
    --user) USER_TAG="$2"; shift 2 ;;
    --agent-prefix) AGENT_PREFIX="$2"; shift 2 ;;
    --version) MCP_CALL_VERSION="$2"; shift 2 ;;
    --skip-plugin-install) SKIP_PLUGIN_INSTALL=1; shift ;;
    --restart) RESTART_GATEWAY=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  AGENT_ID="${AGENT_PREFIX}-${USER_TAG}"
fi

if [[ -z "$API_KEY" && -z "$JWT" ]]; then
  echo "Provide --api-key or --jwt (or set NIGHTHAWK_API_KEY / NIGHTHAWK_JWT)." >&2
  exit 1
fi

ENV_DIR="${HOME}/.config/agent-brain"
ENV_FILE="${ENV_DIR}/openclaw.env"
OPENCLAW_CONFIG="${HOME}/.openclaw/openclaw.json"
mkdir -p "$ENV_DIR" "$(dirname "$OPENCLAW_CONFIG")"

# Resolve plugin directory: local checkout or stable download location.
# OpenClaw's --link needs a stable on-disk path that persists after install.
resolve_plugin_dir() {
  if [[ -n "${LOCAL_CHECKOUT}" ]]; then
    echo "${LOCAL_CHECKOUT}/plugins/openclaw"
    return
  fi

  local dest="${HOME}/.local/share/agent-brain/openclaw"
  local tmpdir url
  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  if [[ "$AGENT_PLUGINS_REF" == v* ]]; then
    url="https://github.com/${PLUGIN_GITHUB_REPO}/archive/refs/tags/${AGENT_PLUGINS_REF}.tar.gz"
  else
    url="https://github.com/${PLUGIN_GITHUB_REPO}/archive/refs/heads/${AGENT_PLUGINS_REF}.tar.gz"
  fi

  echo "Fetching openclaw plugin files from GitHub..." >&2
  curl -fsSL "$url" | tar -xz -C "$tmpdir"
  local src
  src="$(ls -d "$tmpdir"/*/plugins/openclaw)"

  mkdir -p "$dest"
  cp -R "$src/." "$dest/"
  echo "$dest"
}

# Install mcp-call binary to DEST.
# Local dev checkouts delegate to the full fetch script (supports go build fallback).
# Remote installs download directly from GitHub releases.
install_mcp_call() {
  local dest="$1"
  mkdir -p "$(dirname "$dest")"

  if [[ -n "${LOCAL_CHECKOUT}" && -f "${LOCAL_CHECKOUT}/scripts/fetch-mcp-call.sh" ]]; then
    export MCP_CALL_VERSION
    "${LOCAL_CHECKOUT}/scripts/fetch-mcp-call.sh" "$dest"
    return
  fi

  local os_name arch asset repo ver url tmp
  case "$(uname -s)" in
    Darwin) os_name=darwin ;;
    Linux)  os_name=linux ;;
    *) echo "unsupported OS: $(uname -s)" >&2; return 1 ;;
  esac
  case "$(uname -m)" in
    x86_64|amd64) arch=amd64 ;;
    arm64|aarch64) arch=arm64 ;;
    *) echo "unsupported arch: $(uname -m)" >&2; return 1 ;;
  esac

  asset="mcp-call-${os_name}-${arch}"
  repo="${NIGHTHAWK_MCP_CALL_REPO:-realnighthawk/agent-plugins}"
  ver="${MCP_CALL_VERSION:-latest}"
  if [[ -z "$ver" || "$ver" == "latest" ]]; then
    url="https://github.com/${repo}/releases/latest/download/${asset}"
  else
    url="https://github.com/${repo}/releases/download/v${ver#v}/${asset}"
  fi

  tmp="${dest}.$$.tmp"
  echo "Downloading mcp-call (${asset})..."
  curl -fsSL "$url" -o "$tmp"
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"
  echo "Installed ${dest} from release"
}

PLUGIN_DIR="$(resolve_plugin_dir)"

echo "Installing mcp-call..."
install_mcp_call "${PLUGIN_DIR}/bin/mcp-call"

cat >"$ENV_FILE" <<EOF
# Agent Brain OpenClaw — generated by install.sh
export NIGHTHAWK_MCP_URL=${MCP_URL}
export NIGHTHAWK_AGENT_ID=${AGENT_ID}
export NIGHTHAWK_AGENT_PREFIX=${AGENT_PREFIX}
EOF
chmod 600 "$ENV_FILE"

if [[ -n "$JWT" ]]; then
  echo "export NIGHTHAWK_JWT=${JWT}" >>"$ENV_FILE"
else
  echo "export NIGHTHAWK_API_KEY=${API_KEY}" >>"$ENV_FILE"
fi

if [[ "$SKIP_PLUGIN_INSTALL" -eq 0 ]]; then
  echo "Linking plugin with OpenClaw..."
  openclaw plugins install --link "${PLUGIN_DIR}"
fi

merge_openclaw_config() {
  local auth_key auth_val mcp_header_key mcp_header_val
  if [[ -n "$JWT" ]]; then
    auth_key="jwt"
    auth_val="$JWT"
    mcp_header_key="Authorization"
    mcp_header_val="Bearer ${JWT}"
  else
    auth_key="apiKey"
    auth_val="$API_KEY"
    mcp_header_key="X-API-Key"
    mcp_header_val="$API_KEY"
  fi

  local base='{}'
  if [[ -f "$OPENCLAW_CONFIG" ]]; then
    base="$(cat "$OPENCLAW_CONFIG")"
  fi

  echo "$base" | jq \
    --arg url "$MCP_URL" \
    --arg auth_key "$auth_key" \
    --arg auth_val "$auth_val" \
    --arg agent_id "$AGENT_ID" \
    --arg mcp_header_key "$mcp_header_key" \
    --arg mcp_header_val "$mcp_header_val" \
    '
    .plugins = (.plugins // {}) |
    .plugins.slots = (.plugins.slots // {}) |
    .plugins.slots.memory = "agent-brain" |
    .plugins.entries = (.plugins.entries // {}) |
    .plugins.entries["agent-brain"] = {
      enabled: true,
      config: ({
        url: $url,
        agentId: $agent_id,
        autoRecall: true,
        autoCapture: true,
        recallLimit: 8
      } + (if $auth_key == "jwt" then {jwt: $auth_val} else {apiKey: $auth_val} end))
    } |
    .mcp = (.mcp // {}) |
    .mcp["agent-brain"] = {
      type: "streamable-http",
      url: $url,
      headers: ({
        "X-Agent-ID": $agent_id,
        "X-Session-ID": "openclaw-session"
      } + (if $mcp_header_key == "Authorization" then {Authorization: $mcp_header_val} else {"X-API-Key": $mcp_header_val} end))
    }
    ' >"${OPENCLAW_CONFIG}.tmp" && mv "${OPENCLAW_CONFIG}.tmp" "$OPENCLAW_CONFIG"

  echo "Updated ${OPENCLAW_CONFIG}"
}

merge_openclaw_config

if [[ "$RESTART_GATEWAY" -eq 1 ]]; then
  echo "Restarting OpenClaw gateway..."
  openclaw gateway restart
fi

echo ""
echo "Installed Agent Brain for OpenClaw"
echo "  Plugin path: ${PLUGIN_DIR}"
echo "  MCP URL:     ${MCP_URL}"
echo "  Agent ID:    ${AGENT_ID}"
echo "  Env file:    ${ENV_FILE}"
echo "  Config:      ${OPENCLAW_CONFIG}"
echo ""
echo "Optional: source ${ENV_FILE} in your shell for env-based overrides."
echo ""
echo "Server checklist:"
echo "  1. Memory Explorer → Settings: register agent \"${AGENT_ID}\""
echo "  2. openclaw gateway restart"
echo "  3. openclaw plugins inspect agent-brain --runtime --json"
