#!/usr/bin/env bash
# Install Agent Brain OpenClaw plugin (hosted SSE + lifecycle hooks).
#
# Usage:
#   ./plugins/openclaw/install.sh \
#     --url https://agent-memory.nighthawklabs.org/sse \
#     --agent-id openclaw-you \
#     --api-key YOUR_KEY
#
# Remote:
#   curl -fsSL .../plugins/openclaw/install.sh | bash -s -- --api-key ...
set -euo pipefail

SCRIPT_PATH="${BASH_SOURCE[0]}"
# shellcheck source=../../scripts/lib/install-repo.sh
. "$(cd "$(dirname "$SCRIPT_PATH")/../.." && pwd)/scripts/lib/install-repo.sh"

ROOT="$(plugins_repo_root "$SCRIPT_PATH")"
PLUGIN_DIR="${ROOT}/plugins/openclaw"

MCP_URL="https://agent-memory.nighthawklabs.org/sse"
AGENT_ID=""
API_KEY="${NIGHTHAWK_API_KEY:-}"
JWT="${NIGHTHAWK_JWT:-}"
USER_TAG="${USER:-you}"
AGENT_PREFIX="openclaw"
MCP_CALL_VERSION="${MCP_CALL_VERSION:-latest}"
SKIP_PLUGIN_INSTALL=0
RESTART_GATEWAY=0

usage() {
  sed -n '2,11p' "$SCRIPT_PATH" | sed 's/^# \{0,1\}//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url) MCP_URL="$2"; shift 2 ;;
    --agent-id) AGENT_ID="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    --jwt) JWT="$2"; shift 2 ;;
    --user) USER_TAG="$2"; shift 2 ;;
    --agent-prefix) AGENT_PREFIX="$2"; shift 2 ;;
    --version) MCP_CALL_VERSION="$2"; shift 2 ;;
    --skip-plugin-install) SKIP_PLUGIN_INSTALL=1; shift ;;
    --restart) RESTART_GATEWAY=1; shift ;;
    -h|--help) usage 0 ;;
    *) echo "unknown arg: $1" >&2; usage 1 ;;
  esac
done

if [[ -z "$AGENT_ID" ]]; then
  AGENT_ID="${AGENT_PREFIX}-${USER_TAG}"
fi

if [[ -z "$API_KEY" && -z "$JWT" ]]; then
  echo "Provide --api-key or --jwt (or set NIGHTHAWK_API_KEY / NIGHTHAWK_JWT)." >&2
  exit 1
fi

ENV_DIR="${HOME}/.config/agent-brain"
ENV_FILE="${ENV_DIR}/openclaw.env"
OPENCLAW_CONFIG="${HOME}/.openclaw/openclaw.json"
mkdir -p "$ENV_DIR" "$(dirname "$OPENCLAW_CONFIG")"

echo "Installing mcp-call..."
export MCP_CALL_VERSION
"${ROOT}/scripts/fetch-mcp-call.sh" "${PLUGIN_DIR}/bin/mcp-call"

cat >"$ENV_FILE" <<EOF
# Agent Brain OpenClaw — generated by install.sh
export NIGHTHAWK_MCP_URL=${MCP_URL}
export NIGHTHAWK_AGENT_ID=${AGENT_ID}
export NIGHTHAWK_AGENT_PREFIX=${AGENT_PREFIX}
EOF
chmod 600 "$ENV_FILE"

if [[ -n "$JWT" ]]; then
  echo "export NIGHTHAWK_JWT=${JWT}" >>"$ENV_FILE"
else
  echo "export NIGHTHAWK_API_KEY=${API_KEY}" >>"$ENV_FILE"
fi

if [[ "$SKIP_PLUGIN_INSTALL" -eq 0 ]]; then
  if command -v openclaw >/dev/null 2>&1; then
    echo "Linking plugin with OpenClaw..."
    openclaw plugins install --link "${PLUGIN_DIR}" || {
      echo "Note: plugin may already be linked. Run: openclaw plugins list" >&2
    }
  else
    echo "openclaw CLI not on PATH — after installing OpenClaw, run:" >&2
    echo "  openclaw plugins install --link ${PLUGIN_DIR}" >&2
  fi
fi

merge_openclaw_config() {
  if ! command -v jq >/dev/null 2>&1; then
    echo "jq not found — merge templates/openclaw.jsonc into ${OPENCLAW_CONFIG} manually." >&2
    return 1
  fi

  local auth_key auth_val mcp_header_key mcp_header_val
  if [[ -n "$JWT" ]]; then
    auth_key="jwt"
    auth_val="$JWT"
    mcp_header_key="Authorization"
    mcp_header_val="Bearer ${JWT}"
  else
    auth_key="apiKey"
    auth_val="$API_KEY"
    mcp_header_key="X-API-Key"
    mcp_header_val="$API_KEY"
  fi

  local base='{}'
  if [[ -f "$OPENCLAW_CONFIG" ]]; then
    base="$(cat "$OPENCLAW_CONFIG")"
  fi

  echo "$base" | jq \
    --arg url "$MCP_URL" \
    --arg auth_key "$auth_key" \
    --arg auth_val "$auth_val" \
    --arg agent_id "$AGENT_ID" \
    --arg mcp_header_key "$mcp_header_key" \
    --arg mcp_header_val "$mcp_header_val" \
    '
    .plugins = (.plugins // {}) |
    .plugins.slots = (.plugins.slots // {}) |
    .plugins.slots.memory = "agent-brain" |
    .plugins.entries = (.plugins.entries // {}) |
    .plugins.entries["agent-brain"] = {
      enabled: true,
      config: ({
        url: $url,
        agentId: $agent_id,
        autoRecall: true,
        autoCapture: true,
        recallLimit: 8
      } + (if $auth_key == "jwt" then {jwt: $auth_val} else {apiKey: $auth_val} end))
    } |
    .mcp = (.mcp // {}) |
    .mcp["agent-brain"] = {
      type: "streamable-http",
      url: $url,
      headers: ({
        "X-Agent-ID": $agent_id,
        "X-Session-ID": "openclaw-session"
      } + (if $mcp_header_key == "Authorization" then {Authorization: $mcp_header_val} else {"X-API-Key": $mcp_header_val} end))
    }
    ' >"${OPENCLAW_CONFIG}.tmp" && mv "${OPENCLAW_CONFIG}.tmp" "$OPENCLAW_CONFIG"

  echo "Updated ${OPENCLAW_CONFIG}"
}

merge_openclaw_config || true

if [[ "$RESTART_GATEWAY" -eq 1 ]] && command -v openclaw >/dev/null 2>&1; then
  echo "Restarting OpenClaw gateway..."
  openclaw gateway restart || true
fi

echo ""
echo "Installed Agent Brain for OpenClaw"
echo "  Plugin path: ${PLUGIN_DIR}"
echo "  MCP URL:     ${MCP_URL}"
echo "  Agent ID:    ${AGENT_ID}"
echo "  Env file:    ${ENV_FILE}"
echo "  Config:      ${OPENCLAW_CONFIG}"
echo ""
echo "Optional: source ${ENV_FILE} in your shell for env-based overrides."
echo ""
echo "Server checklist:"
echo "  1. Memory Explorer → Settings: register agent \"${AGENT_ID}\""
echo "  2. openclaw gateway restart"
echo "  3. openclaw plugins inspect agent-brain --runtime --json"
